### ISSUE TITLE
'bSwitch' is not a known element

### ISSUE THREAD

**Issue by sabb123** [JulioWar/jw-bootstrap-switch-ng2#13]
We are using angular4.

**Package.json** is like below
  "jw-bootstrap-switch-ng2": "^1.0.4",

**systemjs** 
   'jw-bootstrap-switch-ng2': 'lib/jw-bootstrap-switch-ng2'
   'jw-bootstrap-switch-ng2': {
                main: './dist/index.js',
                defaultExtension: 'js'
            }

**app.module.ts**
import { JWBootstrapSwitchModule } from "jw-bootstrap-switch-ng2";
@NgModule({ imports:[JWBootstrapSwitchModule]})

Gulpfile has copied the jw-bootstrap-switch-ng2 folder

Getting the error 'bSwitch' is not a known element:
1. If 'bSwitch' is an Angular component, then verify that it is part of this module.
What am I doing wrong? Are there any dependencies that needs to be brought in?

Thank you

**Comment by JulioWar** [comment]
Hello @sabb123 

Can you check if the configuration of the`systemjs.config.js`  that is in the readme of this library work for you?

It's something like this: 
```javascript
System.config({
        paths: {
            'npm:': 'node_modules/'
        },
        map: {
            ...,
            'jw-bootstrap-switch-ng2': 'npm:jw-bootstrap-switch-ng2'
        },
        packages: {
            ...,
            'jw-bootstrap-switch-ng2': {
                main: './dist/index.js',
                defaultExtension: 'js'
            }
        }
    });
```

**Comment by sabb123** [comment]
Yes, you are correct. Systemjs.config.js file did not point to the right path. Thank you
