### ISSUE TITLE
Changing the color and also responsiveness

### ISSUE THREAD

**Issue by sabb123** [JulioWar/jw-bootstrap-switch-ng2#14]
1. Is it possible to change the color of the part of the switch that is white in color? Not the color of the ON and OFF but the other side.

2.  Is this component responsive? I want to be able to see the switch in different devices.

Thank you

**Comment by JulioWar** [comment]
Hello @sabb123 

1. Check the issue #9 if you want to change the color of the label.
2. The responsiveness depend of the project. you can resize the switch when the resolution of the window change. You just need to use the property `size`, check the readme for more information. If you want other behavior for your especific implementation, you have to change your css.

> Please check the other issues before create a new one, to focus in to the specific issue separately

Good Luck
