### ISSUE TITLE
TS2322: Type 'null' is not assignable to type 'number'.

### ISSUE THREAD

**Issue by Qowy** [JulioWar/jw-bootstrap-switch-ng2#15]
Shouldn't line 71 in directive.ts be:

` private _dragStart: any = null;`
instead of
` private _dragStart: number = null;`

Technically it should probably be ` private _dragStart?: number = undefined;` but declaring it any keeps it in line with _dragEnd

**Comment by JulioWar** [comment]
Hello @Qowy 

Thanks. I will change it. I didn't see it.

**Comment by JulioWar** [comment]
Just one question @Qowy , When did you see that error? When you are trying to add it in a module?  what version of typescript are you using ?

**Comment by JulioWar** [comment]
update the library and try again. 
Let me know if you have an issue, if not, please close this issue

**Comment by Qowy** [comment]
Thank you will try it tomorrow.

 I just installed it via npm and set it up in my app.module.ts I got the error during loading of the page (which I think uses webpack)

I am using Typescript 2.5 and I think my typescript configuration enforces strict null checking, which seems to be the default since a few versions ago according to me googling this error.

**Comment by Qowy** [comment]
Works fine thank you.
