### ISSUE TITLE
jw-bootstrap-switch-ng2\dist\directive.ts is not part of the compilation output

### ISSUE THREAD

**Issue by pinktoadette** [JulioWar/jw-bootstrap-switch-ng2#19]
Keeps throwing me this. I upgraded all my nod_modules, then this appeared. 
ERROR in ./node_modules/jw-bootstrap-switch-ng2/dist/directive.ts
Module build failed: Error: Path\user-app\node_module
s\jw-bootstrap-switch-ng2\dist\directive.ts is not part of the compilation output
. Please check the other error messages for details.
    at AngularCompilerPlugin.getCompiledFile (Path\us
er-app\node_modules\@ngtools\webpack\src\angular_compiler_plugin.js:629:23)
    at plugin.done.then (Path\user-app\node_modules\@
ngtools\webpack\src\loader.js:467:39)
    at process._tickCallback (internal/process/next_tick.js:109:7)
 @ ./node_modules/jw-bootstrap-switch-ng2/dist/index.js 10:18-40
 @ ./src/app/app.module.ts
 @ ./src/main.ts
 @ multi webpack-dev-server/client?http://0.0.0.0:0 ./src/main.ts

**Comment by JulioWar** [comment]
Hello @pinktoadette can you share the version of angular and the version of this library that you are using?

**Comment by JulioWar** [comment]
Hey guys, Thanks for reporting the issue.  I Think is an issue cause by angular version so please give some time to figure it out what is wrong.

Thanks for using my library.

**Comment by JulioWar** [comment]
Hello @pinktoadette 

I think this alternative workaround for now. Try to change the `tsconfig.json`.
```json
{
  "compileOnSave": false,
  "compilerOptions": {
    "outDir": "./dist/out-tsc",
    "sourceMap": true,
    "declaration": false,
    "moduleResolution": "node",
    "emitDecoratorMetadata": true,
    "experimentalDecorators": true,
    "target": "es5",
    "typeRoots": [
      "node_modules/@types"
    ],
    "lib": [
      "es2017",
      "dom"
    ]
  },
  "include":[
    "src/**/*",
    "node_modules/jw-bootstrap-switch-ng2/dist/index.ts"
  ]
}
```
## Include the library.

Please let me kwow if that works for you and I will continue working to fix the problem.

**Comment by pinktoadette** [comment]
It’s working fine now.
Thanks!

**Comment by leomayer** [comment]
Does not work here with Angular 5.0.5.
Additionally the build fails with enabled option `--aot`

**Comment by JulioWar** [comment]
Hello guys, sorry for the delay. 
I was searching about this and a found these issues that are related: 
- https://github.com/angular/angular-cli/issues/8284
- https://github.com/angular/angular/issues/20091

If some of you found some solution that I can implement will be awesome, I am little bussy right now... but I'm gonna try to solve this issue as soon is possible

**Comment by bpatrik** [comment]
Hi,

I also did some google and found this comment (in the issue mentioned):
https://github.com/angular/angular-cli/issues/8284#issuecomment-341417325

It says that libs should not include `.ts` files, only compiled ones.

You can check what other libs are doing.
These seem to working fine for me:
[ng2-slim-loading-bar](https://www.npmjs.com/package/ng2-slim-loading-bar), [ng2-toaster](https://www.npmjs.com/package/ng2-toastr)

**Comment by JulioWar** [comment]
Hello @bpatrik, sorry for my delay but this last days I was working on other projects and I didn't test that.
Can you please tell what version of nodejs do you have ?

Today I try to install the last version of node js and then I remove the node_module directory and I tried to install all again and for some reason it works.

Can you please try that ?

This is the  version of my dependencies: 
```
Angular CLI: 1.5.0
Node: 8.9.3
OS: win32 x64
Angular: 5.1.2

```
I thinks is releated to the Angular version too

**Comment by JulioWar** [comment]
But yeah, I'm gonna remove the ts files but I just want to test how it works with in IONIC

**Comment by bpatrik** [comment]
Hi,

I think the problem appeared with the latest angular cli and it's (mostly) independent from node.

I'm using these:
```
 "@angular/animations": "^5.1.2",
 "@angular/cli": "1.6.2",
 "@angular/common": "~5.1.2",
 "@angular/compiler": "~5.1.2",
 "@angular/compiler-cli": "^5.1.2",
 "@angular/core": "~5.1.2",
 "@angular/forms": "~5.1.2",
 "@angular/http": "~5.1.2",
 "jw-bootstrap-switch-ng2": "^1.0.8",
 "typescript": "^2.6.2",
```
```
node: v6.9.4
npm: 5.6.0
OS: win 10 x64
```
And I try to compile with this:
```
ng build -prod
```

Adding this to `tsconfig.app.json` soved my problem temporary:
```
 "include":[
    "./**/*",
    "./../node_modules/jw-bootstrap-switch-ng2/dist/index.ts",
    "./../node_modules/jw-bootstrap-switch-ng2/dist/directive.ts"
  ]
```
As far as I understand the problem the latest cli does not include all source(`.ts`) files automatically (which was not a good approach before), but only those that are really source files, so the '.ts' files in the  `node_modules` are excluded by default.

**Comment by JulioWar** [comment]
@bpatrik  I updated the library already, I removed the ts files. Can you try to update the this library and try again ?

**Comment by bpatrik** [comment]
hmm it seems that it solved the issue partially. 
for `ng build` it works, but for `ng build -prod`, i got an error:
```
ERROR in : Unexpected value 'JWBootstrapSwitchModule in <projectroot>/node_modules/jw-bootstrap-switch-ng2/dist/index.js' imported by the module 'AppM
odule in <projectroot>/frontend/app/app.module.ts'. Please add a @NgModule annotation.
```

I'm not sure if this error is still in connection with your library.

**Comment by JulioWar** [comment]
ok,  let me see what can I do

**Comment by JulioWar** [comment]
Hello Guys, I think I finally did it! Please try to download the last version and try again.

**Comment by chelaruc** [comment]
Thank you, @JulioWar, for your work! It's working now ❤️ 😍

**Comment by JulioWar** [comment]
Thanks for the feedback, I'm going to close this issue then.
