### ISSUE TITLE
Switch with icon

### ISSUE THREAD

**Issue by chelaruc** [JulioWar/jw-bootstrap-switch-ng2#22]
Hi,

Have you implemented a switch icon instead of text? I really need this in my projects. Here is an example: 
![screen shot 2017-11-09 at 13 07 41](https://user-images.githubusercontent.com/22840626/32602535-09537c6a-c54f-11e7-99c5-93e17778ad6d.png)

Regards,
Ciprian

**Comment by JulioWar** [comment]
Hi @chelaruc 

No, I don't have an implementation yet. but i can try to do something quickly.

Give me a moment.

**Comment by JulioWar** [comment]
Hello @chelaruc 

I made the changes, now is possible to pass html for the properties `switch-off-text` and `switch-on-text` and you can use it like this:

### With a varible
#### Component
```typescript
...
class ComponentName {
     icon: string = '<i class"icon icon-trash">'
}
```
### View
```html
<bSwitch
                  [switch-on-text]="icon"
                  [switch-off-text]="icon"
                ></bSwitch>
```

### or just defining it in the view
```html
<bSwitch
                  switch-on-text="<i class'icon icon-trash'>"
                  switch-off-text="<i class'icon icon-cog'>"
                ></bSwitch>
```
Just update the library.

**Comment by chelaruc** [comment]
@JulioWar Thank you!
