### ISSUE TITLE
ERROR in Metadata version mismatch for module

### ISSUE THREAD

**Issue by bosunolanrewaju** [JulioWar/jw-bootstrap-switch-ng2#24]
After installing the module. Running `ng serve` produces the error and angular is unable to compile.

ERROR in Metadata version mismatch for module /my-project/node_modules/jw-bootstrap-switch-ng2/dist/index.d.ts, found version 4, expected 3,resolving symbol AppModule in /my-project/src/app/app.module.ts, resolving symbol AppModule in /my-project/src/app/app.module.ts

Angular: 4.2.4
jw-bootstrap-switch-ng2: 1.0.10

**Comment by JulioWar** [comment]
Hello @bosunolanrewaju, Yes I saw that, I was working on update for angular 5, please downgrade the version to the `1.0.8`. It's the same thing. Sorry for this issue.

**Comment by bosunolanrewaju** [comment]
@JulioWar Thanks for your response, I will give that a shot.

**Comment by bosunolanrewaju** [comment]
@JulioWar, `1.0.8` works as expected. Thanks
