### ISSUE TITLE
I cannot use it with the command ng serve

### ISSUE THREAD

**Issue by bighansen** [JulioWar/jw-bootstrap-switch-ng2#27]
I cannot use it with the command 
>>ng serve
in this way the web page cannot be opened.

The only way I can use with this plug-in is
>>ng build
and then deploy the web in the nginx

What should I do to solve this problem?

**Comment by bighansen** [comment]
I'm sorry, this is a misunderstanding and I solved by myself.
By the way, is it the element that I cannot adjust the size arbitrarily？

**Comment by JulioWar** [comment]
Hi @bighansen, Sorry I don't understand your question 
>is it the element that I cannot adjust the size arbitrarily？
