### ISSUE TITLE
Not working with ChangeDetectionStrategy.OnPush

### ISSUE THREAD

**Issue by Flyover-ArtSk** [JulioWar/jw-bootstrap-switch-ng2#28]
Not working with
`changeDetection: ChangeDetectionStrategy.OnPush`

Switcher initializing only on mouse hover :(

![ng-switcher-bug](https://user-images.githubusercontent.com/1798696/39139366-68f5d9b2-472a-11e8-9ab2-8ed6948c3cbd.gif)

**Comment by JulioWar** [comment]
Hello @Flyover-ArtSk, Can you replicate this in a repository or share the code to check that ?

**Comment by ahadjithoma** [comment]
Hello @JulioWar  we have the same problem. 

I wrote a mini demo instackblitz  to replicate the bug. 
[demo](https://stackblitz.com/edit/angular-jn4qxb)

Can you take a look please? thanks

**Comment by JulioWar** [comment]
Thanks for the demo. I will check it

**Comment by JulioWar** [comment]
Thanks for your patience guys, The version 2.0.2 is available. Test it and let me know if it's working fine.
