### ISSUE TITLE
Disable functionality

### ISSUE THREAD

**Issue by ahadjithoma** [JulioWar/jw-bootstrap-switch-ng2#29]
It seems that when the switch is inside a form and that form is disabled, the switch is still enabled. 
I know about the `switch-disabled="condition"` but it would be more helpful if i could disable the Switch based on the form status. 

for example: 

```
<!-- .html -->
<form [formGroup]="myForm">
  <bSwitch></bSwitch>
  <input type="text" />
</form>
```

```
// .ts
...
myForm.disable()
```

i am expecting the bSwitch to be disabled, but only the input type is disabled.

**Comment by JulioWar** [comment]
Hello @andreash92 
I didn't know about that funtionality, I going to take the time to do that in the weekend.

Thanks

**Comment by ahadjithoma** [comment]
thanks i really appreciate it!

**Comment by MarcosRibeiroJesus** [comment]
Same here, good to hear about the solution soon. Thanks @JulioWar! =))

**Comment by JulioWar** [comment]
Thanks for your patience guys, The version 2.0.2 is available. Test it and let me know if it's working fine.
