### ISSUE TITLE
changeState documentation

### ISSUE THREAD

**Issue by bpatrik** [JulioWar/jw-bootstrap-switch-ng2#31]
Hi

Sorry for the not well formatted issue.
In the docs the example code has the wrong event name:
``` 
[switch-handle-width]="handleWidth"
          [switch-base-class]="'bootstrap-switch'"
          (onChangeState)="onChange($event)">
  </bSwitch>
```
I know the readme says at two other places that its actually `changeState`, but it still took me 1 hour to fix this issue, since I was only looking at the example. :/
I would encourage using the new notation in the example too.
Thx!

Best,
Patrik

**Comment by JulioWar** [comment]
Sorry @bpatrik 

I totally forgot to do it.
