### ISSUE TITLE
Add Angular 7 support

### ISSUE THREAD

**Issue by iCodr8** [JulioWar/jw-bootstrap-switch-ng2#32]
Please add support for angular 7

**Comment by JulioWar** [comment]
Hello @iCodr8 

What is the error the you get ?

**Comment by nabilelmahiri** [comment]
I have an issue too when upgraded to angular 7, it gives me this error :

`npm WARN jw-bootstrap-switch-ng2@2.0.2 requires a peer of @angular/common@^6.0.0-rc.0 || ^6.0.0 but none is installed. You must install peer dependencies yourself.`

**Comment by JulioWar** [comment]
Hello @nabilelmahiri 

Thanks for your feedback, I going to check that, because I actually did it without an issue so maybe I am missing something in the process.

Can you create a repository where you can reproduce the problem? Maybe that would more easy for me to see it and fix it.

**Comment by nabilelmahiri** [comment]
My pleasure @JulioWar I am doing it right now

**Comment by nabilelmahiri** [comment]
This is the repository i have created https://github.com/nabilelmahiri/angular-creativetim-theme ,
you can reproduce the error running npm install

Thanks for your help

**Comment by nabilelmahiri** [comment]
@JulioWar any news my friend ?

**Comment by JulioWar** [comment]
Sorry @nabilelmahiri 

I will check  it on the weekend

**Comment by JulioWar** [comment]
Hello @nabilelmahiri, I think I resolved the issue in the new release 2.0.4.  Can you tested and confirm or deny that It's been resolved?

Thanks for your patient

**Comment by nabilelmahiri** [comment]
Hello @JulioWar the last errors are gone, but now we have this error, i think still doensnt support the last updates of angular 7

`├── UNMET PEER DEPENDENCY @angular/common@7.2.2
├── UNMET PEER DEPENDENCY @angular/core@7.2.2
└── jw-bootstrap-switch-ng2@2.0.4`

**Comment by JulioWar** [comment]
@nabilelmahiri  I want to ask you, do you still can run the command `ng serve` ? When do you get that error ?

I did something  else, but if that doesn't work I don't know what to do. I using peer dependencies because  in that way I don't need to imported in the project and the core of angular doesn't have breaking changes.

I hope the last change works for you.

**Comment by nabilelmahiri** [comment]
Hello my friend @JulioWar , the problem is solved in the last version, thank you some much.

**Comment by JulioWar** [comment]
Hello @iCodr8, Can you test the last changes and see if that was your issue too ? Feel free to open this
