### ISSUE TITLE
Angular4

### ISSUE THREAD

**Issue by nitimmerman** [JulioWar/jw-bootstrap-switch-ng2#7]
Hi there,

Thanks for creating this nice-looking switch component.
Could you please upgrade  the dependencies to Angular4? We've just upgraded our project to Angular4 and the switch is still working, however it would be nice if we could get rid of the warning message in NPM

Many thanks,
Nico

**Comment by JulioWar** [comment]
Hi @nitimmerman and Thanks for using my component.
I change the `package.json` in this [lines](https://github.com/JulioWar/jw-bootstrap-switch-ng2/blob/master/package.json#L27) as the [documentation of npm say](https://docs.npmjs.com/misc/semver), but it is not seems to work.

**Comment by nitimmerman** [comment]
Hi @JulioWar,
Thanks for your quick reply. I've upgraded to the latest version of your library (1.0.2) and the warning messages disappeared. So, to me everything is fine now

Many Thanks.

Nico

**Comment by JulioWar** [comment]
Ok, Thanks for your confirmation.
