### ISSUE TITLE
Make OFF label text visible, when the value is true and the switch is ON

### ISSUE THREAD

**Issue by jainanuj0812** [JulioWar/jw-bootstrap-switch-ng2#8]
While using this plugin, one limitation that I faced is that the label for the off option is not visible. Can we have a option to make the label for both the option visible all the time

**Comment by JulioWar** [comment]
I don't understand what are you trying to do but if you want to show the value of the `off option` you can change the `label text`  when the value has change.

```html
<bSwitch
          [switch-label-text]="(state) ?  'OFF' :  'ON' "
          switch-off-text="ON"
          switch-on-text="OFF"
          [(ngModel)]="state">
  </bSwitch>
```

**Comment by JulioWar** [comment]
or you want something like this **(without `text label`)**
![image](https://www.bypeople.com/wp-content/uploads/2016/04/toggle-switches-c2b7-css-demo.jpg)

**Comment by jainanuj0812** [comment]
@JulioWar, Thanks man! ya that's what I want.
